# cd example/llm
python src/incontext_learning.py \
    --engine "ChatGPT" \
    --model_id "gpt-3.5-turbo" \
    --api_key "your-api-key" \
    --base_url "https://your-base-url" \
    --temperature 0.3 \
    --top_p 0.9 \
    --max_tokens 100 \
    --task "re" \
    --language "ch" \
    --in_context true \
    --text_input "艾伦就读于湖滨中学，在这里他遇到和自己一样对计算机编程痴迷的盖茨。" \
    --domain "情感识别" \
    --labels "感情" \
    --head_entity "艾伦" \
    --head_type "人物" \
    --tail_entity "计算机编程" \
    --tail_type "事件"