  CMeIE {
    task: "ere"
    dataset: "CMeIE"
    data_dir: ${ASP}/data/CMeIE/
    model_dir: ${ASP}/data/CMeIE/
    log_dir: ${ASP}/data/CMeIE/
    log_root: ${ASP}/data/CMeIE/
    max_segment_len: 256
    use_amp: true
    optimizer: "adamw"
    plm_learning_rate: 3e-5
    task_learning_rate: 3e-4
    plm_scheduler: "linear_with_warmup"
    task_scheduler: "linear_with_warmup"
    warmup_ratio: 0.05
    adam_eps: 1e-8
    adam_weight_decay: 0.1
    init_std: 0.02  
    max_grad_norm: 1 
    batch_size: 8
    gradient_accumulation_steps: 1
    num_epochs: 200
    activation: "relu"
    dropout_rate: 0.3
    feature_emb_size: 20
    hidden_size: 1500
    num_typing_classes: 11
    num_linking_classes: 44
    beam_size: 1
    eval_frequency: 500
    report_frequency: 20
    plm_tokenizer_name: t5-small
    plm_learning_rate: 5e-5
    task_learning_rate: 1e-4
    plm_pretrained_name_or_path: t5-base
  }
